//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace API_Pato_V2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CLIENTE_ENVIO_SMS
    {
        public int DNI { get; set; }
        public Nullable<System.DateTime> Fecha { get; set; }
        public string Telefono { get; set; }
        public string Estado { get; set; }
    }
}
