//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace API_Pato_V2.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class BI_PRODEntities : DbContext
    {
        public BI_PRODEntities()
            : base("name=BI_PRODEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
    
        public virtual ObjectResult<sp_api_VISTA_360_CLIENTE_Result> sp_api_VISTA_360_CLIENTE(string varDNI)
        {
            var varDNIParameter = varDNI != null ?
                new ObjectParameter("varDNI", varDNI) :
                new ObjectParameter("varDNI", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_api_VISTA_360_CLIENTE_Result>("sp_api_VISTA_360_CLIENTE", varDNIParameter);
        }
    }
}
